ViewModels/HomeViewModel.cs
namespace LojaVirtual.ViewModels;

public class HomeViewModel
{
    public List<LojaVirtual.Models.Produto> Produtos { get; set; }
    public List<LojaVirtual.Models.CarrinhoCompraItem> Carrinho { get; set; }
}

Controllers/FaturasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LojaVirtual.Data;
using LojaVirtual.Models;
using Microsoft.AspNetCore.Authorization;

namespace LojaVirtual.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FaturasController : Controller
    {
        private readonly AppDbContext _context;

        public FaturasController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Faturas
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Faturas.Include(f => f.Pedido);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Faturas/Details/5
        public async Task<IActionResult> Details(string? id)
        {
            if (id == null || _context.Faturas == null)
            {
                return NotFound();
            }

            var fatura = await _context.Faturas
                .Include(f => f.Pedido)
                .FirstOrDefaultAsync(m => m.FaturaId == id);
            if (fatura == null)
            {
                return NotFound();
            }

            return View(fatura);
        }

        // GET: Faturas/Create
        public IActionResult Create()
        {
            ViewData["PedidoId"] = new SelectList(_context.Pedidos, "PedidoId", "Cep");
            return View();
        }

        // POST: Faturas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FaturaId,PedidoId,FaturaStatus,ExternalReference,IPAddress,PreferenceMPId,Preco,MetodoDePagamento,CreatedDate,LastUpdatedDate")] Fatura fatura)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fatura);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PedidoId"] = new SelectList(_context.Pedidos, "PedidoId", "Cep", fatura.PedidoId);
            return View(fatura);
        }

        // GET: Faturas/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Faturas == null)
            {
                return NotFound();
            }

            var fatura = await _context.Faturas.FindAsync(id);
            if (fatura == null)
            {
                return NotFound();
            }
            ViewData["PedidoId"] = new SelectList(_context.Pedidos, "PedidoId", "Cep", fatura.PedidoId);
            return View(fatura);
        }

        // POST: Faturas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("FaturaId,PedidoId,FaturaStatus,ExternalReference,IPAddress,PreferenceMPId,Preco,MetodoDePagamento,CreatedDate,LastUpdatedDate")] Fatura fatura)
        {
            if (id != fatura.FaturaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fatura);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FaturaExists(fatura.FaturaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PedidoId"] = new SelectList(_context.Pedidos, "PedidoId", "Cep", fatura.PedidoId);
            return View(fatura);
        }

        // GET: Faturas/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Faturas == null)
            {
                return NotFound();
            }

            var fatura = await _context.Faturas
                .Include(f => f.Pedido)
                .FirstOrDefaultAsync(m => m.FaturaId == id);
            if (fatura == null)
            {
                return NotFound();
            }

            return View(fatura);
        }

        // POST: Faturas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Faturas == null)
            {
                return Problem("Entity set 'AppDbContext.Faturas'  is null.");
            }
            var fatura = await _context.Faturas.FindAsync(id);
            if (fatura != null)
            {
                _context.Faturas.Remove(fatura);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FaturaExists(string id)
        {
          return (_context.Faturas?.Any(e => e.FaturaId == id)).GetValueOrDefault();
        }
    }
}

Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LojaVirtual.Data;
using LojaVirtual.Models;
using Microsoft.AspNetCore.Authorization;

namespace LojaVirtual.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PedidosController : Controller
    {
        private readonly AppDbContext _context;

        public PedidosController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Pedidos
        public async Task<IActionResult> Index()
        {
              return _context.Pedidos != null ? 
                          View(await _context.Pedidos.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.Pedidos'  is null.");
        }

        // GET: Pedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.PedidoId == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Pedidos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PedidoId,Nome,Sobrenome,Endereco,Cep,Estado,Cidade,Email,PedidoEnviado,token")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Pedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Pedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PedidoId,Nome,Sobrenome,Endereco,Cep,Estado,Cidade,Email,PedidoEnviado,token")] Pedido pedido)
        {
            if (id != pedido.PedidoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.PedidoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Pedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pedidos == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.PedidoId == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Pedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pedidos == null)
            {
                return Problem("Entity set 'AppDbContext.Pedidos'  is null.");
            }
            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido != null)
            {
                _context.Pedidos.Remove(pedido);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
          return (_context.Pedidos?.Any(e => e.PedidoId == id)).GetValueOrDefault();
        }
    }
}

Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LojaVirtual.Data;
using LojaVirtual.Models;
using Microsoft.AspNetCore.Authorization;

namespace LojaVirtual.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProdutosController : Controller
    {
        private readonly AppDbContext _context;

        public ProdutosController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Produtos
        public async Task<IActionResult> Index()
        {
              return _context.Produtos != null ? 
                          View(await _context.Produtos.ToListAsync()) :
                          Problem("Entity set 'AppDbContext.Produtos'  is null.");
        }

        // GET: Produtos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.ProdutoId == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // GET: Produtos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produtos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProdutoId,Nome,Preco")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos.FindAsync(id);
            if (produto == null)
            {
                return NotFound();
            }
            return View(produto);
        }

        // POST: Produtos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProdutoId,Nome,Preco")] Produto produto)
        {
            if (id != produto.ProdutoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutoExists(produto.ProdutoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.ProdutoId == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Produtos == null)
            {
                return Problem("Entity set 'AppDbContext.Produtos'  is null.");
            }
            var produto = await _context.Produtos.FindAsync(id);
            if (produto != null)
            {
                _context.Produtos.Remove(produto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutoExists(int id)
        {
          return (_context.Produtos?.Any(e => e.ProdutoId == id)).GetValueOrDefault();
        }
    }
}

Views/Home/ApiKey.cshtml
@{
    ViewBag.Title = "Desenvolvedor";
    Layout = "_Layout";
}

<div class="text-center">
    <h2 class="my-3">Seja bem-vindo desenvolvedor</h2>
    <h1>@ViewBag.ApiKey</h1>
    <h3>Essa é sua chave de API</h3>
</div>

Views/Home/Dashboard.cshtml
@model LojaVirtual.ViewModels.ClientDashboardViewModel

@{
    ViewBag.Title = "Dashboard";
    Layout = "_Layout";
}

<h1>Painel do cliente</h1>

<h3>Faturas</h3>
<div class="d-flex">
    @if (Model.faturas == null)
    {
        <h1>
            Nenhuma fatura disponível
        </h1>
    } else {
    @foreach (var item in Model.faturas)
    {
        <div class="w-25 mx-5">
            <p>Pedido @item.PedidoId</p>

            <p>
                Total: R$@item.Preco.ToString().Replace(".", ",")
            </p>
            <p>
                @item.CreatedDate
            </p>
            @if (item.FaturaStatus == "pending")
            {
                <button type="button" class="btn btn-outline-warning">Pendente</button>
            }
            else if (item.FaturaStatus == "approved")
            {
                <button type="button" class="btn btn-outline-success">Aprovado</button>
            }
            <a asp-controller="Home" asp-action="View" asp-route-id="@item.PedidoId">
                <button class="btn btn-primary">
                    Ver detalhes
                </button>
            </a>
        </div>
    }
        
    }
</div>

Views/Home/Index.cshtml
@model LojaVirtual.ViewModels.HomeViewModel
@using Microsoft.AspNetCore.Server.Kestrel.Core
@using System.Security.Cryptography

@{
    ViewData["Title"] = "Início";
}
        <div class="text-center" style="background-color: #15141A !important">
            @if (User.Identity.IsAuthenticated)
            {
                <h2 class="mb-5">
                    Todos os produtos
                </h2>
                <div class="d-flex me-2 flex-wrap justify-content-center">
                    @foreach (var item in Model.Produtos)
                    {
                        <div class="w-auto p-3 mb-3 me-4 border border-1 rounded border-secondary">
                            <img src="@item.ImageUrl" alt="" width="100" height="100">
                            <p>@item.Nome</p>
                            <p>
                                R$@item.Preco.ToString().Replace(".", ",")
                            </p>

                            @if (Model.Carrinho.FirstOrDefault(x => x.ProdutoId == item.ProdutoId) == null)
                            {
                                <a asp-controller="Carrinho" class="btn btn-primary" asp-action="AdicionarItemAoCarrinho" asp-route-id="@item.ProdutoId" asp-route-action="Index" asp-route-controller="Home">Adicionar ao carrinho</a>
                            }
                            else
                            {
                                <a asp-controller="Carrinho" class="btn btn-danger" asp-action="RemoverItemDoCarrinho" asp-route-id="@item.ProdutoId" asp-route-action="Index" asp-route-controller="Home">Remover do carrinho</a>
                            }

                        </div>
                    }
                </div>
                <br/>
                if (@Model.Carrinho.Count > 0)
                {
                    <a asp-controller="Carrinho" asp-action="FinalizarCarrinho">
                        <button type="submit" class="btn" style="background-color: #7474E4; color: #FFF; width: 200px; height:50px; font-family: 'Ubuntu', sans-serif;">
                            Carrinho @Model.Carrinho.Count
                        </button>
                    </a>
                }
                <h1 class="my-5">
                    Desejamos um feliz natal

                </h1>
            }
            else
            {
                <h2>
                    Para ver todos os produtos, <a asp-controller="Account" asp-action="Login">realize o login</a>
                </h2>
            }
        </div>


Views/Home/Painel.cshtml
@{
    ViewBag.Title = "Dashboard administrativa";
}

<h1>Painel do administrador</h1>

<a asp-controller="Produtos" asp-action="Index">Gerenciar produtos</a><br/>
<a asp-controller="Faturas" asp-action="Index">Gerenciar faturas</a><br/>
<a asp-controller="Pedidos" asp-action="Index">Gerenciar pedidos</a><br/>

Views/Home/Suporte.cshtml
@model a.SuporteRequest

@{
    ViewBag.Title = "Suporte";
    Layout = "_Layout";
}

<h1 class="mb-3 mb-2" style="color: #7474E4">
    Suporte
</h1>
<form asp-controller="Home" asp-action="SuporteMail" method="post" class="p-3 border border-0" style="background-color: #23202B;">
    <div class="row g-3">


        <div class="col-sm-6 mb-2">
                <input asp-for="Nome" type="text" class="form-control text-light border border-0"
                       style="background-color: #15141A" id="username" placeholder="Nome" name="username"
                       value="@ViewBag.Nome" required="">
            
            <div class="invalid-feedback">
                Preencha com o nome
            </div>
        </div>

        <div class="col-sm-6 mb-2">
            <input asp-for="Email" type="email" class="form-control text-light border border-0"
                   style="background-color: #15141A" id="email" name="email" placeholder="E-mail" value="@ViewBag.Email"
                   required="">
            <div class="invalid-feedback">
                Preencha com o e-mail.
            </div>
        </div>

        <div class="col-12">
            <textarea asp-for="Mensagem" style="background-color: #15141A" class="form-control text-light border border-0" placeholder="Sua mensagem" style="resize: vertical">

            </textarea>
            <div class="invalid-feedback">
                Preencha com a mensagem.
            </div>
        </div>

    </div>


    <button type="submit" class="btn my-5" style="background-color: #7474E4; color: #FFF; width: 200px; height:50px; font-family: 'Ubuntu', sans-serif;">
        Enviar mensagem
    </button>
    
    @if (TempData["res"] != null)
    {
        <p>
            @TempData["res"]
        </p>
    }
</form>

Views/Home/View.cshtml
@model a.ViewFaturasViewModel

@{
    ViewBag.Title = "Dashboard";
    Layout = "_Layout";
}

<h2>Visualizar fatura</h2>

<p>Status do pagamento: @Model.Fatura.FaturaStatus</p>
<p>Pagamento criado em @Model.Fatura.CreatedDate.ToString()</p>
<p>Ultima alteração em @Model.Fatura.LastUpdatedDate.ToString()</p>

<h2>Visualizar Pedido</h2>

<p>Pedido total: R$@Model.Fatura.Preco.ToString().Replace(".",",")</p>
<p>Itens:</p>
<ul>
    @foreach (var item in Model.PedidoDetalhes)
    {
        <p>@item.Lanche.Nome, quantidade: @item.Quantidade, preço total: R$@item.Preco.ToString().Replace(".",",")</p>
    }
</ul>